client_config_backend: settings
client_config:
  client_id: <your Google API client ID>
  client_secret: <your Google API client secret>

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install